
# port
server:
  port: 9999

# Level logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          # uri: http://localhost:8080
          # Usando Eureka lb:// => load balancing
          uri: lb://customer
          predicates:
            - Path=/api/customers/**

        - id: transaction
          uri: lb://transaction
          predicates:
            - Path=/api/transaction/full-validationst-test
          # Especificamos los filtros de seguridad a aplicar por cada ruta
          filters:
            - name: AuthenticationFiltering


        - id: products
          uri: lb://products
          predicates:
            - Path=/api/products/**
            # Especificando por verbos del request
            - Method=GET,POST
          # Especificamos los filtros de seguridad a aplicar por cada ruta
          filters:
            - name: AuthenticationFiltering