
# port
server:
  port: 9999

# Level logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          # uri: http://localhost:8080
          # Usando Eureka lb:// => load balancing
          uri: lb://customer
          predicates:
            - Path=/api/customers/**

